dist: trusty
sudo: required

language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

env:
  global:
    - CXX=g++-4.9

install: export CXX="g++-4.9"

addons:
  chrome: stable

before_script:
- yarn global add @angular/cli

script: ng t --project @knora/core --watch=false --browsers=ChromeHeadless
