dist: trusty
sudo: required

language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - npm install -g node-gyp

script:
  - yarn ng t --project @knora/core --watch=false --browsers=ChromeHeadless
